# To use these prefixes you need additionally the nerochat.<COLORCODE>
# / indicates disabled!
# This config is configured to be what 2b2t.org has.
bstats-metrics: true
notify-updates: true

whisper:
  from: "&d%player%&d whispers: %message%"
  to: "&dYou whisper to %player%&d: %message%"
hovertext: "&6Message &3%player%"

ignore: "&6Permanently ignoring %player%&6. This is saved in &4/ignorelist."
unignore: "&6No longer permanently ignoring &3%player%"

chatformat: "<%player%&r>"
stripnamecolor: false

consolename: "[console]"

ignorelistsize: 9
prefixes:
  GREEN: ">"
  BLUE: '/'
  RED: '/'
  AQUA: '/'
  GOLD: '/'
  YELLOW: '/'
  GRAY: '/'
  BLACK: '/'
  DARK_GREEN: '/'
  DARK_RED: '/'
  DARK_GRAY: '/'
  DARK_BLUE: '/'
  DARK_AQUA: '/'
  DARK_PURPLE: '/'
  LIGHT_PURPLE: '/'
  ITALIC: '/'
  UNDERLINE: '/'
  BOLD: '/'
  STRIKETHROUGH: '/'

RegexFilter:
  Chat:
    ConsoleNotify: true
    PlayerNotify: true
    SilentMode: false
    CaseInsensitive: true
    Allowed-Regex:
      - '[^A-Za-zА-Яа-яЁё0-9 !%()?>+-_,/:]+'
  Whisper:
    ConsoleNotify: true
    PlayerNotify: true
    SilentMode: false
    CaseInsensitive: true
    Allowed-Regex:
      - '[^A-Za-zА-Яа-яЁё0-9 !%()?>+-_,/:]+'

ReadableFormatting:
  PublicChat: true
